[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd apps/api && npm install"]

[phases.build]
cmds = ["cd apps/api && npm run build"]

[start]
cmd = "cd apps/api && npm start"
