# Railway API Configuration - Force reload
[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd railway-api && npm install"]

[phases.build]
cmds = ["cd railway-api && npm run build"]

[start]
cmd = "cd railway-api && npm start"
